site_name: Classic Kitson Wiki
site_url: https://classickitson.com/wiki/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

docs_dir: wiki-content
site_dir: wiki